[2025-03-05T06:20:17.999+0000] {processor.py:186} INFO - Started process (PID=2552) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:20:17.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:20:18.000+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:20:18.000+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:20:18.002+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:20:18.001+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:20:18.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:20:18.011+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.015 seconds
[2025-03-05T06:20:19.230+0000] {processor.py:186} INFO - Started process (PID=2561) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:20:19.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:20:19.232+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:20:19.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:20:19.236+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:20:19.235+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:20:19.236+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:20:19.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.023 seconds
[2025-03-05T06:20:20.254+0000] {processor.py:186} INFO - Started process (PID=2568) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:20:20.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:20:20.256+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:20:20.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:20:20.261+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:20:20.260+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:20:20.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:20:20.274+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.027 seconds
[2025-03-05T06:20:50.679+0000] {processor.py:186} INFO - Started process (PID=2632) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:20:50.680+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:20:50.681+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:20:50.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:20:50.686+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:20:50.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:20:50.686+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:20:50.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.028 seconds
[2025-03-05T06:21:21.238+0000] {processor.py:186} INFO - Started process (PID=2696) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:21:21.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:21:21.241+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:21:21.240+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:21:21.245+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:21:21.244+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:21:21.245+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:21:21.259+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.026 seconds
[2025-03-05T06:21:51.960+0000] {processor.py:186} INFO - Started process (PID=2760) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:21:51.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:21:51.962+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:21:51.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:21:51.966+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:21:51.965+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:21:51.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:21:51.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.031 seconds
[2025-03-05T06:22:22.485+0000] {processor.py:186} INFO - Started process (PID=2824) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:22:22.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:22:22.488+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:22:22.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:22:22.491+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:22:22.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:22:22.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:22:22.503+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.022 seconds
[2025-03-05T06:22:52.960+0000] {processor.py:186} INFO - Started process (PID=2888) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:22:52.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:22:52.962+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:22:52.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:22:52.966+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:22:52.965+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:22:52.966+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:22:52.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.027 seconds
[2025-03-05T06:23:23.260+0000] {processor.py:186} INFO - Started process (PID=2952) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:23:23.261+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:23:23.262+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:23:23.262+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:23:23.266+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:23:23.265+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:23:23.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:23:23.278+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.024 seconds
[2025-03-05T06:23:53.573+0000] {processor.py:186} INFO - Started process (PID=3016) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:23:53.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:23:53.574+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:23:53.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:23:53.577+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:23:53.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:23:53.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:23:53.586+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.016 seconds
[2025-03-05T06:24:23.829+0000] {processor.py:186} INFO - Started process (PID=3080) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:24:23.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:24:23.831+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:24:23.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:24:23.835+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:24:23.834+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:24:23.835+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:24:23.852+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.029 seconds
[2025-03-05T06:24:54.135+0000] {processor.py:186} INFO - Started process (PID=3144) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:24:54.137+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:24:54.138+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:24:54.138+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:24:54.142+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:24:54.141+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:24:54.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:24:54.154+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.025 seconds
[2025-03-05T06:25:24.408+0000] {processor.py:186} INFO - Started process (PID=3207) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:25:24.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:25:24.411+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:25:24.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:25:24.416+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:25:24.415+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:25:24.416+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:25:24.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.037 seconds
[2025-03-05T06:25:54.807+0000] {processor.py:186} INFO - Started process (PID=3271) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:25:54.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:25:54.809+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:25:54.809+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:25:54.812+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:25:54.811+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:25:54.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:25:54.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.027 seconds
[2025-03-05T06:26:25.146+0000] {processor.py:186} INFO - Started process (PID=3335) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:26:25.148+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:26:25.150+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:26:25.149+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:26:25.156+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:26:25.155+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:26:25.157+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:26:25.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.034 seconds
[2025-03-05T06:26:55.204+0000] {processor.py:186} INFO - Started process (PID=3399) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:26:55.205+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:26:55.206+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:26:55.206+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:26:55.211+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:26:55.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:26:55.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:26:55.228+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.032 seconds
[2025-03-05T06:27:25.826+0000] {processor.py:186} INFO - Started process (PID=3463) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:27:25.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:27:25.829+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:27:25.828+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:27:25.832+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:27:25.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:27:25.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:27:25.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.022 seconds
[2025-03-05T06:27:56.123+0000] {processor.py:186} INFO - Started process (PID=3527) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:27:56.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:27:56.125+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:27:56.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:27:56.128+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:27:56.127+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:27:56.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:27:56.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.019 seconds
[2025-03-05T06:28:12.304+0000] {processor.py:186} INFO - Started process (PID=3528) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:28:12.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:28:12.306+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:28:12.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:28:12.315+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:28:12.314+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:28:12.315+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:28:12.325+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.027 seconds
[2025-03-05T06:28:12.526+0000] {processor.py:186} INFO - Started process (PID=3537) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:28:12.526+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:28:12.527+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:28:12.527+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:28:12.530+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:28:12.529+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:28:12.532+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:28:12.543+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.020 seconds
[2025-03-05T06:28:12.739+0000] {processor.py:186} INFO - Started process (PID=3547) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:28:12.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:28:12.740+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:28:12.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:28:12.747+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:28:12.746+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:28:12.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:28:12.758+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.022 seconds
[2025-03-05T06:28:12.913+0000] {processor.py:186} INFO - Started process (PID=3553) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:28:12.914+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:28:12.914+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:28:12.914+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:28:12.916+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:28:12.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:28:12.917+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:28:12.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.012 seconds
[2025-03-05T06:28:13.950+0000] {processor.py:186} INFO - Started process (PID=3554) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:28:13.951+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:28:13.952+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:28:13.952+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:28:13.957+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:28:13.956+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:28:13.960+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:28:13.971+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.026 seconds
[2025-03-05T06:28:44.555+0000] {processor.py:186} INFO - Started process (PID=3618) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:28:44.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:28:44.557+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:28:44.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:28:44.562+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:28:44.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:28:44.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:28:44.576+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.024 seconds
[2025-03-05T06:29:15.345+0000] {processor.py:186} INFO - Started process (PID=3682) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:29:15.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:29:15.349+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:29:15.349+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:29:15.362+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:29:15.361+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:29:15.365+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:29:15.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2025-03-05T06:29:46.021+0000] {processor.py:186} INFO - Started process (PID=3746) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:29:46.022+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:29:46.023+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:29:46.023+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:29:46.030+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:29:46.029+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:29:46.031+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:29:46.042+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.027 seconds
[2025-03-05T06:30:08.734+0000] {processor.py:186} INFO - Started process (PID=3788) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:30:08.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:30:08.736+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:08.736+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:30:08.741+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:08.740+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:30:08.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:30:08.760+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.034 seconds
[2025-03-05T06:30:09.756+0000] {processor.py:186} INFO - Started process (PID=3789) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:30:09.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:30:09.759+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:09.758+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:30:09.762+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:09.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:30:09.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:30:09.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.029 seconds
[2025-03-05T06:30:39.966+0000] {processor.py:186} INFO - Started process (PID=3852) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:30:39.968+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:30:39.969+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:39.969+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:30:39.975+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:39.974+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 22
    default_args=default_args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-03-05T06:30:39.976+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:30:39.991+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.032 seconds
[2025-03-05T06:30:54.067+0000] {processor.py:186} INFO - Started process (PID=3882) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:30:54.068+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:30:54.069+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:54.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:30:54.078+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:30:54.126+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:54.126+0000] {override.py:1912} INFO - Created Permission View: can read on DAG:fetch_and_store_amazon_books
[2025-03-05T06:30:54.129+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:54.129+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG:fetch_and_store_amazon_books
[2025-03-05T06:30:54.130+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:54.130+0000] {override.py:1912} INFO - Created Permission View: can edit on DAG:fetch_and_store_amazon_books
[2025-03-05T06:30:54.132+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:54.132+0000] {override.py:1912} INFO - Created Permission View: can read on DAG Run:fetch_and_store_amazon_books
[2025-03-05T06:30:54.133+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:54.133+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG Run:fetch_and_store_amazon_books
[2025-03-05T06:30:54.135+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:54.135+0000] {override.py:1912} INFO - Created Permission View: menu access on DAG Run:fetch_and_store_amazon_books
[2025-03-05T06:30:54.136+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:54.136+0000] {override.py:1912} INFO - Created Permission View: can create on DAG Run:fetch_and_store_amazon_books
[2025-03-05T06:30:54.136+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:54.136+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-05T06:30:54.140+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:54.140+0000] {dag.py:3262} INFO - Creating ORM DAG for fetch_and_store_amazon_books
[2025-03-05T06:30:54.143+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:54.143+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to None, run_after=None
[2025-03-05T06:30:54.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.086 seconds
[2025-03-05T06:30:55.089+0000] {processor.py:186} INFO - Started process (PID=3883) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:30:55.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:30:55.090+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:55.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:30:55.099+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:30:55.108+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:55.108+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-05T06:30:55.120+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:55.119+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to None, run_after=None
[2025-03-05T06:30:55.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2025-03-05T06:30:57.435+0000] {processor.py:186} INFO - Started process (PID=3897) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:30:57.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:30:57.436+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:57.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:30:57.452+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:30:57.464+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:57.464+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-05T06:30:57.476+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:30:57.475+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to None, run_after=None
[2025-03-05T06:30:57.485+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.056 seconds
[2025-03-05T06:31:56.407+0000] {processor.py:186} INFO - Started process (PID=40) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:31:56.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:31:56.415+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:31:56.414+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:31:56.429+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:31:56.439+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:31:56.439+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-05T06:31:56.452+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:31:56.451+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to None, run_after=None
[2025-03-05T06:31:56.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.058 seconds
[2025-03-05T06:32:27.150+0000] {processor.py:186} INFO - Started process (PID=110) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:32:27.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:32:27.156+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:32:27.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:32:27.169+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:32:27.191+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:32:27.191+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-05T06:32:27.209+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:32:27.208+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to None, run_after=None
[2025-03-05T06:32:27.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.076 seconds
[2025-03-05T06:32:57.600+0000] {processor.py:186} INFO - Started process (PID=174) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:32:57.601+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:32:57.603+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:32:57.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:32:57.614+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:32:57.628+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:32:57.628+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-05T06:32:57.641+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:32:57.641+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to None, run_after=None
[2025-03-05T06:32:57.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.058 seconds
[2025-03-05T06:33:27.831+0000] {processor.py:186} INFO - Started process (PID=238) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:33:27.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:33:27.836+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:33:27.836+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:33:27.843+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:33:27.856+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:33:27.856+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-05T06:33:27.868+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:33:27.868+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to None, run_after=None
[2025-03-05T06:33:27.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.054 seconds
[2025-03-05T06:33:58.419+0000] {processor.py:186} INFO - Started process (PID=302) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:33:58.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:33:58.423+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:33:58.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:33:58.431+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:33:58.442+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:33:58.441+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-05T06:33:58.452+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:33:58.452+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to None, run_after=None
[2025-03-05T06:33:58.460+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.048 seconds
[2025-03-05T06:34:28.805+0000] {processor.py:186} INFO - Started process (PID=366) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:34:28.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:34:28.808+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:34:28.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:34:28.815+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:34:28.830+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:34:28.830+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-05T06:34:28.842+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:34:28.842+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to None, run_after=None
[2025-03-05T06:34:28.852+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.056 seconds
[2025-03-05T06:34:33.791+0000] {processor.py:186} INFO - Started process (PID=424) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:34:33.791+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:34:33.792+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:34:33.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:34:33.794+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:34:33.794+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 19
    raise Exception(f"Failed to fetch weather data: {response.status_code}")
    ^^^^^
SyntaxError: invalid syntax
[2025-03-05T06:34:33.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:34:33.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.012 seconds
[2025-03-05T06:34:34.810+0000] {processor.py:186} INFO - Started process (PID=425) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:34:34.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:34:34.812+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:34:34.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:34:34.815+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:34:34.814+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 19
    raise Exception(f"Failed to fetch weather data: {response.status_code}")
    ^^^^^
SyntaxError: invalid syntax
[2025-03-05T06:34:34.815+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:34:34.827+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.021 seconds
[2025-03-05T06:35:05.253+0000] {processor.py:186} INFO - Started process (PID=489) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:35:05.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:35:05.255+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:35:05.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:35:05.258+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:35:05.258+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 19
    raise Exception(f"Failed to fetch weather data: {response.status_code}")
    ^^^^^
SyntaxError: invalid syntax
[2025-03-05T06:35:05.259+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:35:05.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.019 seconds
[2025-03-05T06:35:35.815+0000] {processor.py:186} INFO - Started process (PID=553) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:35:35.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:35:35.819+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:35:35.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:35:35.823+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:35:35.822+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 19
    raise Exception(f"Failed to fetch weather data: {response.status_code}")
    ^^^^^
SyntaxError: invalid syntax
[2025-03-05T06:35:35.824+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:35:35.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.024 seconds
[2025-03-05T06:36:06.385+0000] {processor.py:186} INFO - Started process (PID=617) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:36:06.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:36:06.387+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:36:06.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:36:06.391+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:36:06.390+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 19
    raise Exception(f"Failed to fetch weather data: {response.status_code}")
    ^^^^^
SyntaxError: invalid syntax
[2025-03-05T06:36:06.391+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:36:06.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.023 seconds
[2025-03-05T06:36:36.561+0000] {processor.py:186} INFO - Started process (PID=681) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:36:36.562+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:36:36.562+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:36:36.562+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:36:36.564+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:36:36.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 19
    raise Exception(f"Failed to fetch weather data: {response.status_code}")
    ^^^^^
SyntaxError: invalid syntax
[2025-03-05T06:36:36.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:36:36.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.012 seconds
[2025-03-05T06:37:06.693+0000] {processor.py:186} INFO - Started process (PID=732) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:37:06.693+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:37:06.695+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:37:06.695+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:37:06.703+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:37:06.702+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 19
    raise Exception(f"Failed to fetch weather data: {response.status_code}")
    ^^^^^
SyntaxError: invalid syntax
[2025-03-05T06:37:06.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:37:06.718+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.031 seconds
[2025-03-05T06:37:37.259+0000] {processor.py:186} INFO - Started process (PID=796) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:37:37.261+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:37:37.262+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:37:37.262+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:37:37.268+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:37:37.267+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 19
    raise Exception(f"Failed to fetch weather data: {response.status_code}")
    ^^^^^
SyntaxError: invalid syntax
[2025-03-05T06:37:37.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:37:37.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.027 seconds
[2025-03-05T06:37:42.864+0000] {processor.py:186} INFO - Started process (PID=810) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:37:42.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:37:42.865+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:37:42.865+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:37:42.980+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:37:42.979+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T06:37:42.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:37:42.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.131 seconds
[2025-03-05T06:37:43.880+0000] {processor.py:186} INFO - Started process (PID=811) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:37:43.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:37:43.881+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:37:43.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:37:43.928+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:37:43.927+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T06:37:43.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:37:43.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.059 seconds
[2025-03-05T06:38:06.818+0000] {processor.py:186} INFO - Started process (PID=862) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:38:06.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:38:06.820+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:38:06.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:38:06.876+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:38:06.875+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T06:38:06.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:38:06.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.072 seconds
[2025-03-05T06:38:37.323+0000] {processor.py:186} INFO - Started process (PID=926) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:38:37.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:38:37.325+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:38:37.325+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:38:37.376+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:38:37.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T06:38:37.377+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:38:37.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.066 seconds
[2025-03-05T06:39:07.956+0000] {processor.py:186} INFO - Started process (PID=990) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:39:07.957+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:39:07.958+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:39:07.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:39:08.013+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:39:08.012+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T06:39:08.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:39:08.021+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.070 seconds
[2025-03-05T06:39:38.495+0000] {processor.py:186} INFO - Started process (PID=1054) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:39:38.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:39:38.497+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:39:38.497+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:39:38.548+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:39:38.547+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T06:39:38.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:39:38.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.066 seconds
[2025-03-05T06:40:08.830+0000] {processor.py:186} INFO - Started process (PID=1118) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:40:08.831+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:40:08.832+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:40:08.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:40:08.883+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:40:08.882+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T06:40:08.883+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:40:08.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.064 seconds
[2025-03-05T06:40:39.155+0000] {processor.py:186} INFO - Started process (PID=1182) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:40:39.155+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:40:39.156+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:40:39.156+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:40:39.207+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:40:39.206+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T06:40:39.207+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:40:39.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.064 seconds
[2025-03-05T06:41:09.372+0000] {processor.py:186} INFO - Started process (PID=1246) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:41:09.373+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:41:09.374+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:41:09.374+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:41:09.427+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:41:09.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T06:41:09.427+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:41:09.434+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.067 seconds
[2025-03-05T06:41:39.969+0000] {processor.py:186} INFO - Started process (PID=1310) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:41:39.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:41:39.972+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:41:39.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:41:40.024+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:41:40.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T06:41:40.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:41:40.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.069 seconds
[2025-03-05T06:42:10.303+0000] {processor.py:186} INFO - Started process (PID=1374) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:42:10.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:42:10.306+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:42:10.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:42:10.368+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:42:10.367+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T06:42:10.369+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:42:10.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.084 seconds
[2025-03-05T06:42:40.805+0000] {processor.py:186} INFO - Started process (PID=1438) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:42:40.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:42:40.807+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:42:40.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:42:40.861+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:42:40.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T06:42:40.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:42:40.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.069 seconds
[2025-03-05T06:43:11.255+0000] {processor.py:186} INFO - Started process (PID=1502) to work on /opt/airflow/dags/dag.py
[2025-03-05T06:43:11.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T06:43:11.257+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:43:11.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T06:43:11.314+0000] {logging_mixin.py:190} INFO - [2025-03-05T06:43:11.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T06:43:11.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T06:43:11.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.077 seconds
[2025-03-05T07:18:26.713+0000] {processor.py:186} INFO - Started process (PID=41) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:18:26.718+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:18:26.721+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:18:26.721+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:18:26.824+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:18:26.821+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:18:26.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:18:26.842+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.134 seconds
[2025-03-05T07:20:41.839+0000] {processor.py:186} INFO - Started process (PID=46) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:20:41.840+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:20:41.842+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:20:41.842+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:20:41.953+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:20:41.952+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:20:41.954+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:20:41.962+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.126 seconds
[2025-03-05T07:21:12.066+0000] {processor.py:186} INFO - Started process (PID=110) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:21:12.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:21:12.075+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:21:12.075+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:21:12.144+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:21:12.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:21:12.145+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:21:12.153+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.096 seconds
[2025-03-05T07:21:42.692+0000] {processor.py:186} INFO - Started process (PID=174) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:21:42.693+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:21:42.696+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:21:42.696+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:21:42.755+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:21:42.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:21:42.757+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:21:42.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.080 seconds
[2025-03-05T07:22:13.096+0000] {processor.py:186} INFO - Started process (PID=237) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:22:13.099+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:22:13.102+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:22:13.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:22:13.171+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:22:13.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:22:13.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:22:13.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.099 seconds
[2025-03-05T07:22:43.615+0000] {processor.py:186} INFO - Started process (PID=300) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:22:43.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:22:43.617+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:22:43.617+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:22:43.674+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:22:43.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:22:43.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:22:43.687+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.078 seconds
[2025-03-05T07:23:13.856+0000] {processor.py:186} INFO - Started process (PID=364) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:23:13.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:23:13.861+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:23:13.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:23:13.938+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:23:13.937+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:23:13.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:23:13.951+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.102 seconds
[2025-03-05T07:23:44.440+0000] {processor.py:186} INFO - Started process (PID=428) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:23:44.444+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:23:44.446+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:23:44.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:23:44.526+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:23:44.524+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:23:44.527+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:23:44.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.108 seconds
[2025-03-05T07:24:15.035+0000] {processor.py:186} INFO - Started process (PID=492) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:24:15.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:24:15.041+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:24:15.040+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:24:15.111+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:24:15.109+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:24:15.111+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:24:15.120+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.095 seconds
[2025-03-05T07:24:45.576+0000] {processor.py:186} INFO - Started process (PID=556) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:24:45.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:24:45.580+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:24:45.580+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:24:45.649+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:24:45.646+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:24:45.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:24:45.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.113 seconds
[2025-03-05T07:25:16.153+0000] {processor.py:186} INFO - Started process (PID=620) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:25:16.154+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:25:16.158+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:25:16.157+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:25:16.222+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:25:16.221+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:25:16.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:25:16.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.088 seconds
[2025-03-05T07:25:46.550+0000] {processor.py:186} INFO - Started process (PID=684) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:25:46.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:25:46.562+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:25:46.562+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:25:46.655+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:25:46.651+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:25:46.656+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:25:46.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.134 seconds
[2025-03-05T07:26:17.381+0000] {processor.py:186} INFO - Started process (PID=754) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:26:17.383+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:26:17.390+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:26:17.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:26:17.466+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:26:17.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:26:17.468+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:26:17.476+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.102 seconds
[2025-03-05T07:26:47.948+0000] {processor.py:186} INFO - Started process (PID=818) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:26:47.950+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:26:47.954+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:26:47.953+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:26:48.036+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:26:48.033+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:26:48.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:26:48.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.113 seconds
[2025-03-05T07:27:18.481+0000] {processor.py:186} INFO - Started process (PID=882) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:27:18.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:27:18.486+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:27:18.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:27:18.561+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:27:18.558+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:27:18.561+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:27:18.572+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.101 seconds
[2025-03-05T07:27:49.060+0000] {processor.py:186} INFO - Started process (PID=946) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:27:49.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:27:49.067+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:27:49.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:27:49.146+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:27:49.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:27:49.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:27:49.157+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.109 seconds
[2025-03-05T07:28:19.529+0000] {processor.py:186} INFO - Started process (PID=1010) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:28:19.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:28:19.537+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:28:19.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:28:19.623+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:28:19.618+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:28:19.625+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:28:19.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.120 seconds
[2025-03-05T07:28:50.163+0000] {processor.py:186} INFO - Started process (PID=1074) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:28:50.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:28:50.167+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:28:50.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:28:50.221+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:28:50.220+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:28:50.221+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:28:50.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.071 seconds
[2025-03-05T07:29:20.394+0000] {processor.py:186} INFO - Started process (PID=1138) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:29:20.396+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:29:20.399+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:29:20.399+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:29:20.461+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:29:20.458+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:29:20.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:29:20.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.084 seconds
[2025-03-05T07:29:50.735+0000] {processor.py:186} INFO - Started process (PID=1202) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:29:50.738+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:29:50.740+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:29:50.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:29:50.800+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:29:50.798+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:29:50.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:29:50.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.082 seconds
[2025-03-05T07:30:21.081+0000] {processor.py:186} INFO - Started process (PID=1266) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:30:21.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:30:21.089+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:30:21.088+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:30:21.161+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:30:21.157+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:30:21.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:30:21.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.102 seconds
[2025-03-05T07:30:36.399+0000] {processor.py:186} INFO - Started process (PID=1324) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:30:36.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:30:36.404+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:30:36.404+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:30:36.459+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:30:36.457+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:30:36.459+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:30:36.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.072 seconds
[2025-03-05T07:30:37.434+0000] {processor.py:186} INFO - Started process (PID=1325) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:30:37.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:30:37.437+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:30:37.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:30:37.491+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:30:37.491+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:30:37.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:30:37.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.071 seconds
[2025-03-05T07:30:38.486+0000] {processor.py:186} INFO - Started process (PID=1326) to work on /opt/airflow/dags/dag.py
[2025-03-05T07:30:38.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-03-05T07:30:38.487+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:30:38.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-03-05T07:30:38.528+0000] {logging_mixin.py:190} INFO - [2025-03-05T07:30:38.527+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-03-05T07:30:38.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-03-05T07:30:38.535+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.051 seconds
